#![doc = include_str!(env!("FEUILLETAGE_README"))]
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(not(feature = "std"))]
extern crate alloc;

/// Reference index of every `#[derive(feuilletage::Config)]` attribute with a
/// runnable example for each. Documentation-only module.
pub mod attributes;
/// Liberal type coercion helpers (`coerce_to_string`, `coerce_to_bool`, ...).
pub mod coerce;
/// The [`Config`](config::Config) container — load, merge, query, edit.
pub mod config;
/// Source/Level provenance metadata and [`Context`](context::Context).
pub mod context;
/// Deserialization traits [`FromContextValue`](de::FromContextValue) and
/// [`FromParsed`](de::FromParsed), plus primitive implementations.
pub mod de;
/// Fluent edit API ([`ConfigEntry`](edit::ConfigEntry), [`IntoPath`](edit::IntoPath)).
pub mod edit;
/// [`IsEmpty`](empty::IsEmpty) trait for emptiness-aware defaults and serialization.
pub mod empty;
/// [`Error`](error::Error) type, [`ConfigWarning`](error::ConfigWarning), and
/// [`ErrorTracker`](error::ErrorTracker).
pub mod error;
/// Multi-format loading via [`ConfigLoaderBuilder`](loader::ConfigLoaderBuilder).
pub mod loader;
/// Recursive merge with mutability constraints and `__tokeep` / `__toappend`
/// merge modifiers.
pub mod merge;
/// Serialization helpers (`to_yaml`, `to_json`, `to_toml`, `to_format`).
pub mod ser;
/// `%{field}` template interpolation.
pub mod template;
/// Built-in transforms (`trim`, `to_lowercase`, `parse_duration`, ...) and
/// [`TransformRegistry`](transform::TransformRegistry).
pub mod transform;
/// Core value types: [`Value`](value::Value), [`ContextValue`](value::ContextValue),
/// [`MergeModifier`](value::MergeModifier).
pub mod value;

pub use config::Config;
#[cfg(feature = "std")]
pub use config::{edit_file, edit_file_with_format, edit_first_existing, edit_first_writeable};

// Export context types
pub use context::{
    Context, CustomLevel, CustomSource, Format, Level, MutabilityConstraint, Source,
};

pub use de::{AllowMapKeys, FromContextValue, FromParsed, MutabilityInfo};
pub use edit::{ConfigEntry, IntoPath, RemoveResult};
pub use empty::IsEmpty;
pub use error::{ConfigWarning, Error, ErrorTracker};
pub use merge::MutabilityConstraints;
pub use template::{
    extract_field_references, interpolate_template, topological_sort, value_to_string,
    TemplateError,
};

// Export value types
pub use value::{ContextValue, Value};

pub use value::MergeModifier;

/// Insertion-order-preserving map used by object values.
#[cfg(feature = "std")]
pub type OrderedMap<K, V> = indexmap::IndexMap<K, V>;

/// Insertion-order-preserving map used by object values.
#[cfg(not(feature = "std"))]
pub type OrderedMap<K, V> = indexmap::IndexMap<K, V, hashbrown::DefaultHashBuilder>;

/// Implementation dependencies used by code generated by `#[derive(Config)]`.
///
/// This module is public so macro expansions can resolve these crates without
/// requiring downstream crates to declare them. It is not part of Feuilletage's
/// supported public API.
#[doc(hidden)]
pub mod __private {
    pub use crate::OrderedMap as IndexMap;
    #[cfg(not(feature = "std"))]
    pub use alloc::{borrow::Cow, format, string::ToString, vec};
    pub use hashbrown::HashSet;
    pub use indexmap;
    pub use serde;
    pub use serde_json;
    #[cfg(feature = "std")]
    pub use std::{borrow::Cow, format, string::ToString, vec};
}

// Re-export serialization functions
pub use ser::to_format;
#[cfg(feature = "json")]
pub use ser::to_json;
#[cfg(feature = "json")]
pub use ser::to_json_compact;
#[cfg(feature = "toml")]
pub use ser::to_toml;
#[cfg(feature = "yaml")]
pub use ser::to_yaml;

// Re-export loader builder for multi-file loading
#[cfg(feature = "std")]
pub use loader::{loader, ConfigLoaderBuilder};

// Re-export procedural macros
pub use feuilletage_macros::Config;

// Re-export regex for use in generated validation code
#[cfg(feature = "regex")]
pub use regex;

// Re-export chrono for use in generated format validation code
#[cfg(feature = "chrono")]
pub use chrono;

// Re-export hashbrown HashMap for use in generated MutabilityInfo code
// This allows the macro to work in both std and no_std environments
pub use hashbrown::HashMap as MutabilityHashMap;
